#pragma once

#define FG_BLACK		"\x1b[30m"
#define FG_RED      	"\x1b[31m"
#define FG_GREEN    	"\x1b[32m"
#define FG_YELLOW   	"\x1b[33m"
#define FG_BLUE     	"\x1b[34m"
#define FG_MAGENTA  	"\x1b[35m"
#define FG_CYAN     	"\x1b[36m"
#define FG_WHITE    	"\x1b[37m"

#define BG_BLACK    	"\x1b[40m"
#define BG_RED      	"\x1b[41m"
#define BG_GREEN    	"\x1b[42m"
#define BG_YELLOW   	"\x1b[43m"
#define BG_BLUE     	"\x1b[44m"
#define BG_MAGENTA  	"\x1b[45m"
#define BG_CYAN     	"\x1b[46m"
#define BG_WHITE    	"\x1b[47m"

#define UTIL_RESET      "\x1b[0m"
#define UTIL_BOLD       "\x1b[1m"
#define UTIL_ITALICS    "\x1b[3m"
#define UTIL_UNDERLINE  "\x1b[4m"
#define UTIL_REVERSE    "\x1b[7m"
#define UTIL_CLEAR      "\x1b[2J"
#define UTIL_CLEARLINE  "\x1b[2K"
#define UTIL_UP         "\x1b[1A"
#define UTIL_DOWN       "\x1b[1B"
#define UTIL_RIGHT      "\x1b[1C"
#define UTIL_LEFT       "\x1b[1D"
#define UTIL_NEXTLINE   "\x1b[1E"
#define UTIL_LASTLINE   "\x1b[1F"
#define UTIL_BEGIN      "\x1b[0F"
#define UTIL_TOP        "\x1b[0;0H"
#define UTIL_SAVE       "\x1b[s"
#define UTIL_RESTORE    "\x1b[u"
#define UTIL_VISIBLE    "\x1b[?25h"
#define UTIL_INVISIBLE  "\x1b[?25l"

// Uni­code
// code point 	char­acter 	UTF-8
// en­co­ding
// (hex) 	Uni­co­de char­ac­ter name 	Uni­co­de 1.0 char­act­er name (de­pre­ca­ted)
// U+21B4 	↴ 	e2 86 b4 	RIGHT­WARDS ARROW WITH CORNER DOWNWARDS 	RIGHT ARROW WITH CORNER DOWN
// U+21B5 	↵ 	e2 86 b5 	DOWNWARDS ARROW WITH CORNER LEFT­WARDS 	DOWN ARROW WITH CORNER LEFT
// U+21F1 	⇱ 	e2 87 b1 	NORTH WEST ARROW TO CORNER 	
// U+21F2 	⇲ 	e2 87 b2 	SOUTH EAST ARROW TO CORNER 	
// U+231C 	⌜ 	e2 8c 9c 	TOP LEFT CORNER 	
// U+231D 	⌝ 	e2 8c 9d 	TOP RIGHT CORNER 	
// U+231E 	⌞ 	e2 8c 9e 	BOTTOM LEFT CORNER 	
// U+231F 	⌟ 	e2 8c 9f 	BOTTOM RIGHT CORNER 	
// U+23A1 	⎡ 	e2 8e a1 	LEFT SQUARE BRACKET UPPER CORNER 	
// U+23A3 	⎣ 	e2 8e a3 	LEFT SQUARE BRACKET LOWER CORNER 	
// U+23A4 	⎤ 	e2 8e a4 	RIGHT SQUARE BRACKET UPPER CORNER 	
// U+23A6 	⎦ 	e2 8e a6 	RIGHT SQUARE BRACKET LOWER CORNER 	
// U+27D3 	⟓ 	e2 9f 93 	LOWER RIGHT CORNER WITH DOT 	
// U+27D4 	⟔ 	e2 9f 94 	UPPER LEFT CORNER WITH DOT 	
// U+298D 	⦍ 	e2 a6 8d 	LEFT SQUARE BRACKET WITH TICK IN TOP CORNER 	
// U+298E 	⦎ 	e2 a6 8e 	RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER 	
// U+298F 	⦏ 	e2 a6 8f 	LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER 	
// U+2990 	⦐ 	e2 a6 90 	RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER 	
// U+2B94 	⮔ 	e2 ae 94 	FOUR CORNER ARROWS CIRCLING ANTI­CLOCK­WISE 	
// U+300C 	「 	e3 80 8c 	LEFT CORNER BRACKET 	OPENING CORNER BRACKET
// U+300D 	」 	e3 80 8d 	RIGHT CORNER BRACKET 	CLOSING CORNER BRACKET
// U+300E 	『 	e3 80 8e 	LEFT WHITE CORNER BRACKET 	OPENING WHITE CORNER BRACKET
// U+300F 	』 	e3 80 8f 	RIGHT WHITE CORNER BRACKET 	CLOSING WHITE CORNER BRACKET
// U+A71A 	ꜚ 	ea 9c 9a 	MO­DI­FI­ER LET­TER LOWER RIGHT CORNER ANGLE 	
// U+FE41 	﹁ 	ef b9 81 	PRE­SEN­TA­TI­ON FORM FOR VER­TI­CAL LEFT CORNER BRACKET 	GLYPH FOR VERTICAL OPENING CORNER BRACKET
// U+FE42 	﹂ 	ef b9 82 	PRE­SEN­TA­TI­ON FORM FOR VER­TI­CAL RIGHT CORNER BRACKET 	GLYPH FOR VERTICAL CLOSING CORNER BRACKET
// U+FE43 	﹃ 	ef b9 83 	PRE­SEN­TA­TI­ON FORM FOR VER­TI­CAL LEFT WHITE CORNER BRACKET 	GLYPH FOR VERTICAL OPENING WHITE CORNER BRACKET
// U+FE44 	﹄ 	ef b9 84 	PRE­SEN­TA­TI­ON FORM FOR VER­TI­CAL RIGHT WHITE CORNER BRACKET 	GLYPH FOR VERTICAL CLOSING WHITE CORNER BRACKET
// U+FF62 	｢ 	ef bd a2 	HALFWIDTH LEFT CORNER BRACKET 	HALFWIDTH OPENING CORNER BRACKET
// U+FF63 	｣ 	ef bd a3 	HALFWIDTH RIGHT CORNER BRACKET 	HALFWIDTH CLOSING CORNER BRACKET
// U+1D93B 	𝤻 	f0 9d a4 bb 	SIGNWRITING MOVEMENT-WALLPLANE CORNER SMALL 	
// U+1D93C 	𝤼 	f0 9d a4 bc 	SIGNWRITING MOVEMENT-WALLPLANE CORNER MEDIUM 	
// U+1D93D 	𝤽 	f0 9d a4 bd 	SIGNWRITING MOVEMENT-WALLPLANE CORNER LARGE 	
// U+1D93E 	𝤾 	f0 9d a4 be 	SIGNWRITING MOVEMENT-WALLPLANE CORNER ROTATION 	
// U+1D974 	𝥴 	f0 9d a5 b4 	SIGNWRITING MOVEMENT-FLOORPLANE CORNER SMALL 	
// U+1D975 	𝥵 	f0 9d a5 b5 	SIGNWRITING MOVEMENT-FLOORPLANE CORNER MEDIUM 	
// U+1D976 	𝥶 	f0 9d a5 b6 	SIGNWRITING MOVEMENT-FLOORPLANE CORNER LARGE 	